# BT settings
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="LE-Audio Receiver"

# Logging
CONFIG_LOG=y

# Audio Core Features
CONFIG_BT_AUDIO=y
CONFIG_BT_ISO_PERIPHERAL=y
CONFIG_BT_BAP_UNICAST_SERVER=y
CONFIG_BT_ASCS=y
CONFIG_BT_ASCS_MAX_ASE_SNK_COUNT=2
CONFIG_BT_ISO_TX_BUF_COUNT=2
CONFIG_BT_ISO_MAX_CHAN=4
CONFIG_BT_ATT_PREPARE_COUNT=1
CONFIG_BT_EXT_ADV=y

# HCI High-Throughput Buffers
CONFIG_BT_BUF_EVT_RX_SIZE=255
CONFIG_BT_BUF_ACL_RX_SIZE=255
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_CMD_TX_SIZE=255

# Hardware LC3 Codec Settings
CONFIG_FPU=y
CONFIG_LIBLC3=y

# Fixes for strict Android/Samsung LE Audio stacks
CONFIG_BT_CAP_ACCEPTOR=y
CONFIG_BT_ISO_RX_BUF_COUNT=4
CONFIG_BT_ISO_RX_MTU=251
CONFIG_BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE=32

# Cryptographic pairing support (Mandatory for Samsung)
CONFIG_BT_SMP=y
CONFIG_BT_SIGNING=y

# Compliance: Volume Control Renderer Service
CONFIG_BT_VCP_VOL_REND=y

# Expand the internal Bluetooth Receive thread stack size to handle LC3 processing math
CONFIG_BT_RX_STACK_SIZE=4096

# Connection Timing Tuning
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_MAIN_STACK_SIZE=4096